export enum ROLE {
  USER = "USER",
  ADMIN = "ADMIN",
  ADMINISTRATOR = "ADMINISTRATOR",
  SUPEROWNER = "SUPEROWNER",
  SUPERADMIN = "SUPERADMIN",
  OWNER = "OWNER",
}

export enum Environment {
  DEVELOPMENT = "DEVELOPMENT",
  PRODUCTION = "PRODUCTION",
}
